[package]
name = "rust_wordsoup"
version = "0.1.0"
edition = "2024"

[dependencies]
fxhash = "0.2.1"
#pyo3 = "0.26.0"

[dependencies.pyo3]
version = "0.26.0"
features = ["extension-module"]


[package.metadata.maturin]
name = "rust_wordsoup"
