[package]
name = "scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
fxhash = "0.2.1"
serde = "1.0.228"
serde_json = "1.0.145"
spdlog-rs = "0.5.0"

[dependencies.pyo3]
version = "0.26.0"
features = ["extension-module"]


[package.metadata.maturin]
name = "scraper"
